Python/Django/usernameValidation/apps/username/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create$', views.create, name='create'),
    url(r'^success$', views.success, name='success'),
    url(r'^remove/(?P<id>\d+)$', views.remove, name="remove")
]

Python/Django/usernameValidation/usernameValidation/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.username.urls', namespace='username')),
]

Python/Django/usernameValidation/apps/username/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class BookManager(models.Manager):
    def validate_username(self, postData):
        print postData
        errors = []
        if len(postData['username']) < 8:
            errors.append("Username is not valid!")
        if len(postData['username']) >= 16:
            errors.append("Username is not valid!")
        if self.filter(username=postData['username']):
            print "Found duplicate"
            errors.append("Username already exists!")
        response_to_views = {}

        if errors:
            #failed validation
            response_to_views['status'] = False
            response_to_views['errors'] = errors
            #send message to views
        else:
            #passed validation
            #create the username
            user = self.create(username = postData['username'])
            response_to_views['status'] = True
            response_to_views['username'] = user

        return response_to_views

class Username(models.Model):
    username = models.CharField(max_length=16)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = BookManager()

Python/Django/usernameValidation/apps/username/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from .models import Username
from django.contrib import messages

def index(request):
    return render(request, 'username/index.html')

def create(request):
    if request.method == 'POST':
        
        response_from_models = Username.objects.validate_username(request.POST)

        if response_from_models['status']:
        #     # passed the validation
        #     # save soemthign in session
        #     # redirect to a different page
            request.session['user'] = request.POST['username']
            user = request.POST['username']

            return redirect('username:success')
        else: 
        #     # send a message to the client
            for error in response_from_models['errors']:
                messages.error(request, error)
    return redirect('username:index')

def success(request):
    context={'usernames': Username.objects.all()}
    return render(request, 'username/success.html', context)

def remove(request, id):
    try: 
        del request.session['user']
    except: 
        pass
    current_user = Username.objects.filter(id=id)
    Username.objects.filter(id=id).delete()

    return redirect('username:success')

Python/Django/usernameValidation/apps/username/templates/username/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Username Validator</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/username_style.css' %}">

</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <h1>{{ message }}</h1>
        {% endfor %}
    {% endif %}
    <form action="{% url 'username:create' %}" method="POST">
        {% csrf_token %}
        <p>Username: <input type="text" name="username"></p>
        <input type="submit" value="Submit"/>
    </form>
    
</body>
</html>

Python/Django/usernameValidation/apps/username/templates/username/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Username Validator</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/success.css' %}">

</head>
<body>
    {% csrf_token %}
    {% if request.session.user %}
        <h1>The username you entered ({{ request.session.user }}) is valid.  Thank you!</h1>
    {% endif %}
    <h3>Usernames entered</h3>
    <table>
        {% for username in usernames %}
        <tr>
            <td>{{ username.username }}</td>
            <td>{{ username.created_at }}</td>
            <td><a href="remove/{{ username.id }}">delete</a></td>
        </tr>
        {% endfor %}
    </table>
    
</body>
</html>