Python/Django/dojo_secrets_v2/dojo_secrets/apps/secrets/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.secrets, name='secrets'),
    url(r'^process$', views.process, name='process'),
    url(r'^popular$', views.popular, name='popular'),
    url(r'^delete_secret/(?P<id>\d+)/(?P<return_to>\w+)$', views.delete_secret, name='delete_secret'),
    url(r'^like/(?P<id>\d+)/(?P<return_to>\w+)$', views.like, name='like'),
]

Python/Django/dojo_secrets_v2/dojo_secrets/dojo_secrets/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.logreg.urls', namespace='logreg')),
    url(r'^secrets', include('apps.secrets.urls', namespace='secrets')),
]

Python/Django/dojo_secrets_v2/dojo_secrets/apps/secrets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import datetime
from ..logreg.models import User

class SecretManager(models.Manager):
    def add_like(self, secret_id, liker_id):
        if len( User.objects.filter( user_likes__id = secret_id ).filter( id = liker_id ) ) == 0:
            self.get( id = secret_id ).likes.add( User.objects.get( id = liker_id ) )

# Create your models here.
class Secret(models.Model):
    secret = models.TextField(max_length=1000)
    author = models.ForeignKey(User, related_name="secrets")
    likes = models.ManyToManyField(User, related_name="user_likes")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = SecretManager()

Python/Django/dojo_secrets_v2/dojo_secrets/apps/logreg/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages


def index(request):
    context ={
        "all_users": User.objects.all()
    }
    return render(request, 'logreg/index.html', context)

def register(request):
    if request.method == 'POST':
        response_from_models = User.objects.validate_registration(request.POST)

        if response_from_models['status']:
            request.session['user_id'] = response_from_models['user'].id
            return redirect('secrets:secrets')
        else:
            for error in response_from_models['errors']:
                messages.error(request, error)
            return redirect('logreg:index')

def login(request):
    if request.method == 'POST':
        response_from_models = User.objects.validate_login(request.POST)
        if response_from_models['status']:
            request.session['user_id'] = response_from_models['user'].id
            return redirect('secrets:secrets')
        else:
            for error in response_from_models['errors']:
                messages.error(request, error)
    return redirect('logreg:index')

Python/Django/dojo_secrets_v2/dojo_secrets/apps/secrets/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, reverse
from ..logreg.models import User
from .models import Secret
from django.db.models import Count
import datetime

def secrets(request):
    if 'user_id' in request.session:
        context={
            "user": User.objects.get(id=request.session['user_id']),
            "secrets": Secret.objects.all().annotate(total_likes=Count('likes')).order_by('-created_at')[:5]
        }
            # .annotate(age=(datetime.datetime.now()-'created_at'))

        return render(request,'secrets/secrets.html', context)
    else:
        return redirect( reverse( "logreg:index" ) ) 

def process(request):
    if request.method == 'POST':
        user = User.objects.get(id=request.session['user_id'])
        new_secret = Secret.objects.create(secret = request.POST['secret'], author=user)
    return redirect('secrets:secrets')

def popular(request):
    if 'user_id' in request.session:
        context={
            "user": User.objects.get(id=request.session['user_id']),
            "secrets": Secret.objects.all().annotate(total_likes=Count('likes')).order_by('-total_likes', '-created_at')
        }
        return render(request, 'secrets/popular.html', context)
    else: 
        return redirect( reverse( "login:index" ) ) 

def delete_secret(request, id, return_to):
    Secret.objects.get(id=id).delete()
    return_html = 'secrets:' + return_to
    return redirect( reverse(return_html))

def like(request, id, return_to):
    return_html = 'secrets:' + return_to
    Secret.objects.add_like(id, request.session['user_id'])
    return redirect( reverse(return_html))
    
    
    

Python/Django/dojo_secrets_v2/dojo_secrets/apps/logreg/templates/logreg/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dojo Secrets</title>
    {% load staticfiles %}
	<link rel="stylesheet" href="{% static 'logreg/css/index_style.css' %}">

</head>
<body>
    <div class="main_content">
      <fieldset>
        <legend>Register</legend>
        <form class="register" action="/register" method="post">
            {% csrf_token %}
          <label for="first_name">
            First Name
            <input type="text" name="first_name">
          </label>
          <label for="last_name">
            Last Name
            <input type="text" name="last_name">
          </label>
          <label for="email">
            Email
            <input type="email" name="email">
          </label>
          <label for="password">
            Password
            <input type="password" name="password">
          </label>
          <label for="password_confirmation">
            Confirm Password
            <input type="password" name="password_confirmation">
          </label>
          <button type="submit" name="button">Register</button>
        </form>
      </fieldset>
      <fieldset>
        <legend>Login</legend>
        <form class="login" action="/login" method="POST">
            {% csrf_token %}
          <label for="email">
            Email
            <input type="email" name="email">
          </label>
          <label for="password">
            Password
            <input type="password" name="password">
          </label>
          <button type="submit" name="button">Login</button>
        </form>
      </fieldset>
      {% if messages %}
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    {% endif %}
    <p></p>
    
      <h1>All Users</h1>
      <table>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>password</th>
          <th>created_at</th>
        </tr>
        {% if all_users %}
          {% for user in all_users %}
            <tr>
              <td>{{ user.first_name }}</td>
              <td>{{ user.last_name }}</td>
              <td>{{ user.email }}</td>
              <td>{{ user.password }}</td>
              <td>{{ user.created_at }}</td>
            </tr>
          {% endfor %}
        {% endif %}
      </table>
    
    </div>
</body>
</html>

Python/Django/dojo_secrets_v2/dojo_secrets/apps/secrets/templates/secrets/popular.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'secrets/css/secrets_style.css' %}">
    <title>Dojo Secrets</title>
</head>
<body>
    <h1>Most Popular Secrets...</h1>
    <a href='{% url "secrets:secrets" %}'>Back</a>
    
    <h2>Recent Secrets...</h2>
    {% csrf_token %}
    {% if secrets %}
        {% for secret in secrets %}
            <p>{{ secret.secret }} ({{ secret.created_at }}) <span class='likes'>{{ secret.total_likes }} likes</span>
            {% if secret.author.id == request.session.user_id %}
                <strong>You posted this </strong><a href='{% url "secrets:delete_secret" id=secret.id return_to="popular" %}'> Remove</a>
            {% else %}
                {% if user in secret.likes.all %}
                    <strong>You liked this</strong>
                {% else %}
                    <a href='{% url "secrets:like" id=secret.id return_to="popular" %}'>Like</a>
                {% endif %}
            {% endif %}
            </p>
        {% endfor %}
    {% endif %}
</body>
</html>

Python/Django/dojo_secrets_v2/dojo_secrets/apps/secrets/templates/secrets/secrets.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'secrets/css/secrets_style.css' %}">
    <title>Dojo Secrets</title>
</head>
<body>
    <h1>Hello, {{ user.first_name }}!</h1>
    <form action='{% url 'secrets:process' %}' method='POST'>
        {% csrf_token %}
        <textarea rows='5' cols='60' name='secret' placeholder='Your secret here...'></textarea></br>
        <input type='submit' name='submit' id="submit" value='Post'>
        <a href='{% url "secrets:popular" %}'>Most Popular Secrets</a>
    </form>
    <h2>Recent Secrets...</h2>
    {% csrf_token %}
    {% if secrets %}
        {% for secret in secrets %}
            <p>{{ secret.secret }} ({{ secret.created_at|timesince }}) <span class='likes'>{{ secret.total_likes }} likes</span>
            {% if secret.author.id == request.session.user_id %}
                <strong>You posted this </strong><a href='{% url "secrets:delete_secret" id=secret.id return_to="secrets" %}'> Remove</a>
                
            {% else %}
                {% if user in secret.likes.all %}
                    <strong>You liked this</strong>
                {% else %}
                    <a href='{% url "secrets:like" id=secret.id return_to="secrets" %}'>Like</a>
                {% endif %}
            {% endif %}
            </p>
        {% endfor %}
    {% endif %}
</body>
</html>